; KALEIDOSCOPE PROGRAM FOR CROMEMCO DAZZLER; 
; PROVIDED BY BILL SUDBRINK
; CONVERTED INTO TASM SOURCE BY RICHARD CINI; JUNE 2, 2010; ALTERNATIVE VERSION
; CONVERTED TO MAC VERSION J. MONAHAN 12/6/2013 (Flipped CR/LF's)
; MODIFIED TO RETURN TO CP/M BY UDO MUNK; APRIL 24, 2015
; MODIFIED TO USE CP/M BDOS BY UDO MUNK; MAY 11, 2016


; ASCII CONSTANTS
LF		EQU	0AH
CR		EQU	0DH

; CPM BDOS EQUATES
BDOS		EQU	5
CONSTAT		EQU	11
PRINT		EQU	9

	ORG	100H

 	DI			;WE DON'T KNOW, HOW INTERRUPTS WORKS IN THIS SYSTEM, 
 				;SO WE DISABLE THEM. [SP] IS PROBABLY OK FOR A SMALL PROGRAM LIKE THIS

	LXI	SP,100H
 	LXI	D,SIGNON	;PRINT A WELCOME MESSAGE ON CONSOLE
	MVI	C,PRINT
	CALL	BDOS
 
	MVI	A,81H		;DISPLAY AT 0200H
	OUT 	0EH
	MVI	A,30H
	OUT	0FH	
	
L000B:
	PUSH	B
	PUSH	D
	PUSH	H
	MVI	C,CONSTAT	;GET CONSOLE STATUS
	CALL	BDOS
	POP	H
	POP	D
	POP	B
	ORA	A
	JZ	NOABORT		;NO KEY PRESSED, CONTINUE
	RST	0		;ELSE RETURN TO CP/M

NOABORT:
	MOV	A,B
	RRC
 	RRC
 	ANA 	D
 	ADD	C
 	MOV	C,A
 	RRC
 	RRC
 	ANA	D
  	MOV 	L,A
  	MOV 	A,B
  	SUB 	L
 	MOV 	B,A
 	PUSH 	B
  	PUSH 	D
  	PUSH 	H
  	LXI 	D,0000H
  	MOV 	A,H
  	ANI 	1FH
  	RAR
  	JC 	L002B
  	MOV 	E,A	; ORIGINAL CODES FOR $7B (MOV A,E) 	
 	RLC
  	RLC
  	RLC
  	RLC
  	MOV 	D,A	; ORIGINAL CODES FOR $7A (MOV A,D)
 
L002B:	MVI 	H,08H
  	CALL 	L005D
  	
  	MOV 	A,B
   	CMA
  	MOV 	B,A
  	MVI	H,06H
  	CALL 	L005D
  	
 	MOV 	A,C
 	CMA
 	MOV 	C,A
 	MVI 	H,02H
  	CALL 	L005D
  	
  	MOV 	A,B
  	CMA
  	MOV 	B,A
  	MVI 	H,04H
  	CALL 	L005D
  	
  	POP 	H
  	POP 	D
  	POP 	B
  	DCR 	E
  	JNZ 	L000B
  	
  	INR 	B
  	INR 	C
  	MVI 	E,3FH
  	DCR 	H
  	JNZ 	L000B
  	
  	INR 	D
  	MVI 	H,1FH
  	JMP 	L000B
 
L005D:	MOV 	A,C
  	ANI 	0F8H
  	RAL
  	MOV 	L,A
  	MOV	A,H
 	ACI 	00H
 	MOV 	H,A
 	MOV 	A,B
 	ANI 	0F8H
 	RAR
 	RAR
 	RAR
 	RAR
 	PUSH 	PSW
 	ADD 	L
 	MOV 	L,A
	POP 	PSW
	MOV 	A,M
 	JC 	L007A
 	
 	ANI 	0F0H
 	ADD 	E
 	MOV 	M,A
 	RET
 
L007A:	ANI 	0FH
 	ADD 	D
 	MOV 	M,A
 	RET
 
SIGNON:	DB	CR,LF,'Cromemco Dazzler KSCOPE Program. '
	DB	'Hit some key to return to CP/M',CR,LF,LF,'$'
             
	END
