#!/usr/bin/expect -f
# SPDX-License-Identifier: GPL-2.0-or-later
set timeout 60
log_file -noappend suite/tests/dirtest-dev1-m80.txt
source [file join [file dirname [info script]] cpmsim-path.exp]
spawn $cpmsim -z -d /tmp/dirtest-m80
expect "A>"
send "B:\r"
expect "B>"
send "M80 =DIRTEST\r"
expect "B>"
send "L80 DIRTEST,DIRTEST/N/E\r"
expect "B>"
send "DIR DIRTEST.*\r"
expect "B>"
send "\034"
expect eof
