#!/usr/bin/expect -f
set diskdir [lindex $argv 0]
set logfile [lindex $argv 1]
set emulator [lindex $argv 2]
set timeout 30
log_file -noappend $logfile
spawn $emulator -z -d $diskdir
expect "A>"
send -- "PHYS015 A\r"
expect "Bdos Err On A: Bad Sector"
send "x"
expect "RETURNED"
expect "A>"
send -- "PHYS015 A\r"
expect "Bdos Err On A: Bad Sector"
send "x"
expect "RETURNED"
expect "A>"
send -- "PHYS015 N\r"
expect "RETURNED"
expect "A>"
send "\034"
expect eof
