#!/usr/bin/expect -f
set diskdir [lindex $argv 0]
set logfile [lindex $argv 1]
set timeout 90
log_file -noappend $logfile
spawn cpmsim -z -d $diskdir
expect "A>"

send "EDGE43\r"
expect "A>"
send "ZRET43\r"
expect "A>"
send "EDGE43\r"
expect "A>"
send "FN043\r"
expect "A>"
send "EDGE43\r"
expect "A>"
send "OVER43\r"
expect "A>"
send "EDGE43\r"
expect "A>"
send "MAXOK43\r"
expect "MAXOK43 EXECUTED"
expect "A>"
send "MAXBAD43\r"
expect "BAD LOAD"
expect "A>"
send "\034"
expect eof
